export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_ADDITIONAL = 'ADD_ADDITIONAL';
export const REMOVE_ADDITIONAL = 'REMOVE_ADDITIONAL';
export const SEND_DATA = 'SEND_DATA';